#!/usr/bin/python3.4

"""
Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""


def fibonacci(max_any_term):
   prev_term = 1
   next_term = 2
   fibList = []
   fibList.append(prev_term)
   fibList.append(next_term)

   while (prev_term + next_term) < max_any_term:
      third_term = prev_term + next_term
      fibList.append(third_term)
      prev_term = next_term
      next_term = third_term

   return fibList

sum = 0
for n in fibonacci(4000000):
   if (n % 2) == 0:
      sum += n

print(sum)


